### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by omaraltayyan** [fholzer/docker-nginx-brotli#35]
with the release of AWS's new graviton2 instances, it's becoming more important for popular packages to support ARM64 architecture to benefit from the new servers,

can we consider building this image for arm64 to support running nginx on the new servers?

**Comment by fholzer** [comment]
Good point. I'd probably need to completely change the automated build process. Not sure if I will manage to look into this during the weekend, or maybe next weekend. Seems like a bigger change that needs a lot of reading up on and testing.

Memo to myself:
https://docs.docker.com/docker-hub/builds/advanced/
https://hub.docker.com/r/ckulka/multi-arch-example (check links in "Known limitations")

**Comment by ruizmarc** [comment]
Hi! Thanks for all your efforts @fholzer, is there any progress on this? M1 Mac users and ARM servers users would love this update, that includes me :P

**Comment by quentincaffeino** [comment]
Hello @ruizmarc, I'm also using brotli with nginx and developed container for myself, however my solution is different from this repo. I don't build whole nginx container but only shared objects required for nginx to use brotli. This allows for greater freedom since I can include those SOs in any nginx setup during container build by simply copying them and tweaking nginx configuration. (also resulting container is less that 1mb since it only contains SOs so it doesn't really affect build times)

I don't have Apple M1 so I can't test if it works or not so if you are still interested could you please check out [example](https://github.com/quentincaffeino/docker-nginx-brotli-so/tree/master/example) in my repo.

Whole build pipeline is done using github cicd.

**Comment by ruizmarc** [comment]
Hi!

Sounds like a great idea @quentincaffeino! Thanks for the effort 👍 

FYI I have moved to this drop-in nginx brotli module from an alpine package so everything have become much easier now with alpine 3.13: https://pkgs.alpinelinux.org/package/edge/main/x86/nginx-mod-http-brotli

**Comment by fholzer** [comment]
Platforms:
* amd64
* arm64
* ppc64le

Provided on master (stable) and mainline branches. latest (stable) tag is updated on docker hub already, mainline and version tagged images are still building, should be published about an hour from now, or two.

In case anyone needs any other platforms, let me know.

**Comment by realivanjx** [comment]
is it possible to have architecture specific tags? i need to build my web with amd64 because arm64 emulation is slow but the nginx will run on arm64. thanks.

**Comment by fholzer** [comment]
I don't think that that's how docker builds work. I think docker will always pick the an image with the architecture that you're currently building on. So build on amd64, `docker build` will use the amd64 image. If you build on arm64, it will use that image for building. You can't mix amd64 and arm64 just like that.
What I'm trying to say it that even if there was an architecture specific image with the arch as tag, it wouldn't do what you want it to to IMHO.

**Comment by realivanjx** [comment]
nvm. i can achieve what i wanted by specifying the sha256 of the arm64 image. thanks.
